-- ============================================================
-- Generated by wallust — DO NOT EDIT BY HAND.
-- Template: ~/.config/wallust/templates/colors-hyprland.lua
-- Regenerate: scripts/wallust_swww.sh  (or wallust run <img>)
-- ============================================================

return {
    background = 0xff030511,
    foreground = 0xffadbedd,
    color0     = 0xff030511,
    color1     = 0xffF58D6F,
    color2     = 0xff355099,
    color3     = 0xff56649D,
    color4     = 0xff4842B8,
    color5     = 0xff9C63E1,
    color6     = 0xffC25BD0,
    color7     = 0xffadbedd,
    color8     = 0xff79859a,
    color9     = 0xffF58D6F,
    color10    = 0xff355099,
    color11    = 0xff56649D,
    color12    = 0xff4842B8,
    color13    = 0xff9C63E1,
    color14    = 0xffC25BD0,
    color15    = 0xffadbedd,
}
