-- wallust template — Hyprland Lua colors
-- Generated by: wallust run <wallpaper>
-- Target:       ~/.config/hypr/lua/colors_wallust.lua
-- Template:     colors-hyprland.lua
--
-- Colors are 0xAARRGGBB Lua hex numbers (AA=ff = fully opaque).
--  strips the '#' from wallust's hex color, giving RRGGBB.

return {
    background = 0xff0A0000,
    foreground = 0xffF8EDF3,
    color0     = 0xff0A0000,
    color1     = 0xff6F115B,
    color2     = 0xffA12689,
    color3     = 0xffAE5996,
    color4     = 0xffAE5996,
    color5     = 0xffAE5996,
    color6     = 0xffB099A6,
    color7     = 0xffECDDE6,
    color8     = 0xffA59BA1,
    color9     = 0xff941679,
    color10    = 0xffD733B7,
    color11    = 0xffE877C8,
    color12    = 0xffE877C8,
    color13    = 0xffE877C8,
    color14    = 0xffEACCDD,
    color15    = 0xffECDDE6,
}
