-- wallust template — Hyprland Lua colors
-- Generated by: wallust run <wallpaper>
-- Target:       ~/.config/hypr/lua/colors_wallust.lua
-- Template:     colors-hyprland.lua
--
-- Colors are 0xAARRGGBB Lua hex numbers (AA=ff = fully opaque).
--  strips the '#' from wallust's hex color, giving RRGGBB.

return {
    background = 0xff1D1C1E,
    foreground = 0xffAED7F1,
    color0     = 0xff434245,
    color1     = 0xff16141E,
    color2     = 0xff161926,
    color3     = 0xff0E304D,
    color4     = 0xff143F5F,
    color5     = 0xff126498,
    color6     = 0xff126AA0,
    color7     = 0xff83BEE2,
    color8     = 0xff5C859E,
    color9     = 0xff1E1A28,
    color10    = 0xff1E2133,
    color11    = 0xff134067,
    color12    = 0xff1B537F,
    color13    = 0xff1886CB,
    color14    = 0xff188DD6,
    color15    = 0xff83BEE2,
}
