-- wallust template — Hyprland Lua colors
-- Generated by: wallust run <wallpaper>
-- Target:       ~/.config/hypr/lua/colors_wallust.lua
-- Template:     colors-hyprland.lua
--
-- Colors are 0xAARRGGBB Lua hex numbers (AA=ff = fully opaque).
--  strips the '#' from wallust's hex color, giving RRGGBB.

return {
    background = 0xff1A1C1C,
    foreground = 0xffF3F8F3,
    color0     = 0xff404242,
    color1     = 0xff0E1616,
    color2     = 0xff351D4B,
    color3     = 0xff5F5462,
    color4     = 0xff767B64,
    color5     = 0xff988EA4,
    color6     = 0xffA5B1A5,
    color7     = 0xffE5EDE5,
    color8     = 0xffA0A6A0,
    color9     = 0xff131D1D,
    color10    = 0xff472764,
    color11    = 0xff7F7083,
    color12    = 0xff9EA485,
    color13    = 0xffCBBEDB,
    color14    = 0xffDCECDC,
    color15    = 0xffE5EDE5,
}
