general {
    lock_cmd         = pidof hyprlock || ~/.config/hypr/scripts/hyprlock-watchdog.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = hyprctl dispatch dpms on && (pidof hyprlock > /dev/null || loginctl lock-session)
    inhibit_sleep    = 3
}

listener {
    timeout          = 300
    on-timeout       = hyprctl dispatch dpms off
    on-resume        = hyprctl dispatch dpms on
}

listener {
    timeout          = 900
    on-timeout       = loginctl lock-session
}
