# /* wallust template - colors-kitty */

foreground         #D0D6E8
background         #111114
cursor             #717283

active_tab_foreground     #111114
active_tab_background     #D0D6E8
inactive_tab_foreground   #D0D6E8
inactive_tab_background   #111114

active_border_color   #D0D6E8
inactive_border_color #111114
bell_border_color     #0D0B17

color0      #39393C
color1		#0D0B17
color2		#0D0B17
color3		#38377C
color4		#8D454F
color5		#8345AC
color6		#5C678E
color7		#B4BCD6
color8		#7E8395
color9		#110F1F
color10		#110F1F
color11		#4A4AA6
color12		#BC5C69
color13		#AF5CE5
color14		#7A89BD
color15		#B4BCD6
