# /* wallust template - colors-kitty */

foreground         #F8EDF3
background         #0A0000
cursor             #E790D5

active_tab_foreground     #0A0000
active_tab_background     #F8EDF3
inactive_tab_foreground   #F8EDF3
inactive_tab_background   #0A0000

active_border_color   #F8EDF3
inactive_border_color #0A0000
bell_border_color     #6F115B

color0      #0A0000
color1		#6F115B
color2		#A12689
color3		#AE5996
color4		#AE5996
color5		#AE5996
color6		#B099A6
color7		#ECDDE6
color8		#A59BA1
color9		#941679
color10		#D733B7
color11		#E877C8
color12		#E877C8
color13		#E877C8
color14		#EACCDD
color15		#ECDDE6
